GET http://localhost:3000/users
//retrieve all users


###

POST http://localhost:3000/signup
//register an account
Content-Type: application/json

{
  "fullName": "sebastian",
  "email": "mail1@gmail",
  "password": "password2"
}


###

GET http://localhost:3000/droptables